-- MySQL Script generated by MySQL Workbench
-- Tue 31 May 2022 11:33:43 AM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `sobrenome` VARCHAR(100) NULL,
  `login` VARCHAR(100) NULL,
  `data_nascimento` DATE NULL,
  `genero` VARCHAR(45) NULL,
  `newsletter` TINYINT NULL,
  `senha` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`receitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`receitas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` INT NOT NULL,
  `categoria` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `descricao` TEXT NULL,
  `rendimento` DECIMAL(2,1) NULL,
  `usuario` TIME NULL,
  PRIMARY KEY (`id`, `usuario`, `categoria`),
  INDEX `fk_receitas_1_idx` (`categoria` ASC) VISIBLE,
  INDEX `fk_receitas_2_idx` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_receitas_1`
    FOREIGN KEY (`categoria`)
    REFERENCES `mydb`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receitas_2`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medidas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `volume` DECIMAL(2,10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ingredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ingredientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ingredientes_receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ingredientes_receita` (
  `quantidade` DECIMAL(10,2) NULL,
  `receita` INT NOT NULL,
  `medida` INT NOT NULL,
  `ingrediente` INT NOT NULL,
  INDEX `fk_receita` (`receita` ASC) VISIBLE,
  INDEX `fk_ingrediente` (`ingrediente` ASC) VISIBLE,
  INDEX `fk_medida` (`medida` ASC) VISIBLE,
  PRIMARY KEY (`receita`, `medida`, `ingrediente`),
  CONSTRAINT `id`
    FOREIGN KEY (`receita`)
    REFERENCES `mydb`.`receitas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`ingrediente`)
    REFERENCES `mydb`.`ingredientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`medida`)
    REFERENCES `mydb`.`medidas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comentarios` (
  `usuario` INT NOT NULL,
  `receita` INT NOT NULL,
  `data` DATE NULL,
  `avaliacao` DECIMAL(1,1) NULL,
  `texto` VARCHAR(300) NULL,
  PRIMARY KEY (`usuario`, `receita`),
  INDEX `fk_comentarios_1_idx` (`receita` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_1`
    FOREIGN KEY (`receita`)
    REFERENCES `mydb`.`receitas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_2`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estoque` (
  `usuario` INT NOT NULL,
  `ingrediente` INT NOT NULL,
  `medida` DECIMAL(10,2) NOT NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`usuario`, `ingrediente`, `medida`),
  INDEX `fk_estoque_1_idx` (`ingrediente` ASC) VISIBLE,
  INDEX `fk_estoque_2_idx` (`medida` ASC) VISIBLE,
  CONSTRAINT `fk_estoque_1`
    FOREIGN KEY (`ingrediente`)
    REFERENCES `mydb`.`ingredientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estoque_2`
    FOREIGN KEY (`medida`)
    REFERENCES `mydb`.`medidas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estoque_3`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ingredientes_substitutos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ingredientes_substitutos` (
  `substituto` INT NOT NULL,
  `substituido` INT NOT NULL,
  PRIMARY KEY (`substituto`, `substituido`),
  INDEX `fk_ingredientes_substitutos_2_idx` (`substituto` ASC) VISIBLE,
  CONSTRAINT `fk_ingredientes_substitutos_1`
    FOREIGN KEY (`substituido`)
    REFERENCES `mydb`.`ingredientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingredientes_substitutos_2`
    FOREIGN KEY (`substituto`)
    REFERENCES `mydb`.`ingredientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
